#pragma once

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define USB_VBUS_PIN GP29
#undef  SPLIT_USB_DETECT

#define SPLIT_HAND_PIN GP28
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
//#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP29
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

//#define TT Layer
#define TAPPING_TOGGLE 2

/* Bootmagic Lite key configuration */
#define BOOTMAGIC_LITE_ROW 0  
#define BOOTMAGIC_LITE_COLUMN 2
#define BOOTMAGIC_LITE_ROW_RIGHT 5
#define BOOTMAGIC_LITE_COLUMN_RIGHT 2

/* RGBLIGHT configuration */
#define WS2812_DI_PIN GP27
#define RGBLED_NUM 2
#define RGBLED_MAP { 1, 0 }
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 9
#define RGBLIGHT_EFFECT_CHRISTMAS
#define ENABLE_RGB_MATRIX_BREATHING
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_CHRISTMAS
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#define FORCE_NKRO
