#include QMK_KEYBOARD_H
#include "leds.c"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT( //Alphabet
		LT(6, KC_Q), KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, 
		KC_A, KC_S, KC_D, LT(3, KC_F), LT(5, KC_G), KC_H, LT(4, KC_J), KC_K, KC_L, KC_ENT, 
		LCTL_T(KC_Z), LGUI_T(KC_X), LALT_T(KC_C), LT(1, KC_V), LSFT_T(KC_B), RSFT_T(KC_N), LT(2, KC_M), RALT_T(KC_SPC), RGUI_T(KC_BSPC), LT(1, KC_MPLY)), 

	[1] = LAYOUT( //Numpad and Punctuation
		KC_7, KC_8, KC_9, KC_PDOT, KC_PLUS, KC_ASTR, KC_DLR, KC_COLN, KC_PIPE, KC_GRV, 
		KC_4, KC_5, KC_6, KC_0, KC_MINS, KC_SLSH, KC_HASH, KC_LCBR, KC_RCBR, KC_SCLN, 
		KC_1, KC_2, KC_3, TO(0), KC_DEL, KC_CAPS, LGUI(KC_SPC), KC_COMM, KC_DOT, KC_MUTE),

	[2] = LAYOUT( //Punctuation and Arrow key
		KC_TILD, KC_PERC, KC_UNDS, KC_CIRC, KC_LABK, KC_RABK, KC_HOME, KC_UP, KC_END, KC_PGUP, 
		KC_AT, KC_DQUO, KC_EXLM, KC_QUES, KC_LPRN, KC_RPRN, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, 
		LCTL_T(KC_LBRC), LGUI_T(KC_RBRC), LALT_T(KC_QUOT), KC_AMPR, LSFT_T(KC_EQL), KC_BSLS, TO(0), KC_ESC, KC_TAB, LGUI(KC_ESC)), 

	[3] = LAYOUT( //
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		RGB_TOG, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),

	[4] = LAYOUT( //
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),
		
	[5] = LAYOUT( //
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),

	[6] = LAYOUT( //
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, RGB_TOG,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),

	[7] = LAYOUT( //
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),

	[8] = LAYOUT( //
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX)
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(KC_MPRV, KC_MNXT) },
    [2] = { ENCODER_CCW_CW(LGUI(KC_MINS), LGUI(KC_EQL)) },
    [3] = { ENCODER_CCW_CW(LCTL(KC_MINS), LCTL(KC_PLUS)) },
    [4] = { ENCODER_CCW_CW(KC_UP, KC_DOWN) },
    [5] = { ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [6] = { ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [7] = { ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [8] = { ENCODER_CCW_CW(KC_LEFT, KC_RGHT) }
};
#endif
