#ifndef CONFIG_H
#define CONFIG_H

#define RGB_MATRIX_LED_COUNT 2
#define RGB_MATRIX_SLEEP true
#define RGB_MATRIX_DEFAULT_HUE 255
#define RGB_MATRIX_DEFAULT_SPD 26
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_PINWHEEL

//#define TT Layer
#define TAPPING_TOGGLE 2

/* Bootmagic Lite key configuration */
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

#define FORCE_NKRO

#endif
